# Replace example.com with your domain, and insert a new database password where your_database_root_password appears, And just add the name of the service and your SMTP username and password

version: '3'
services:

  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    environment:
      url: https://example.com
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: your_database_root_password
      database__connection__database: ghost
      # mail__transport: SMTP
      # mail__options__host: {Your Mail Service host}
      # mail__options__port: {Your Mail Service port}
      # mail__options__secureConnection: {true/false}
      # mail__options__service: {Your Mail Service}
      # mail__options__auth__user: {Your User Name}
      # mail__options__auth__pass: {Your Password}
    volumes:
      - /opt/ghost_content:/var/lib/ghost/content

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_database_root_password
    volumes:
      - /opt/ghost_mysql:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /usr/share/nginx/html:/usr/share/nginx/html
